In [1]:
# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [23]:
# Read in the CSV file and convert "?" to NaN
moovies = pd.read_csv(r"C:\Users\Administrateur\Ironhack\LAB\DAFT_212\module_2\Lab_5_ Pivot-Tables-and-Crosstab\archive\movie_metadata.csv", na_values="?" )
moovies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 2. Use crosstabs to show the number of moovies per country

In [24]:
pd.crosstab(moovies.director_name, moovies.country, margins=True, margins_name="Total")

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany,Total
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Hann,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Schneider,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Aaron Seltzer,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Abel Ferrara,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Álex de la Iglesia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Émile Gaudreault,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Éric Tessier,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Étienne Faure,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Total,1,4,1,53,1,4,8,1,1,1,...,6,3,2,5,1,434,3733,1,3,4936

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [28]:
pd.crosstab(moovies.director_name, [moovies.country, moovies.genres], margins=True, margins_name="Total")

country            Afghanistan            Argentina        \
genres                   Drama Crime|Drama|Thriller Drama
director_name
A. Raven Cruz                0                    0     0
Aaron Hann                   0                    0     0
Aaron Schneider              0                    0     0
Aaron Seltzer                0                    0     0
Abel Ferrara                 0                    0     0
...                        ...                  ...   ...
Álex de la Iglesia           0                    0     0
Émile Gaudreault             0                    0     0
Éric Tessier                 0                    0     0
Étienne Faure                0                    0     0
Total                        1                    1     2

country                                                    Aruba  \
genres             Drama|Mystery|Thriller Action|Comedy|Thriller
director_name
A. Raven Cruz                           0                      0
Aaron Hann                              0                      0
Aaron Schneider                         0                      0
Aaron Seltzer                           0                      0
Abel Ferrara                            0                      0
...                                   ...                    ...
Álex de la Iglesia                      0                      0
Émile Gaudreault                        0                      0
Éric Tessier                            0                      0
Étienne Faure                           0                      0
Total                                   1                      1

country                                                   Australia  \
genres             Action|Adventure|Animation|Comedy|Family|Fantasy
director_name
A. Raven Cruz                                                     0
Aaron Hann                                                        0
Aaron Schneider                                                   0
Aaron Seltzer                                                     0
Abel Ferrara                                                      0
...                                                             ...
Álex de la Iglesia                                                0
Émile Gaudreault                                                  0
Éric Tessier                                                      0
Étienne Faure                                                     0
Total                                                             1

country                                                                    \
genres             Action|Adventure|Comedy Action|Adventure|Comedy|Family
director_name
A. Raven Cruz                            0                              0
Aaron Hann                               0                              0
Aaron Schneider                          0                              0
Aaron Seltzer                            0                              0
Abel Ferrara                             0                              0
...                                    ...                            ...
Álex de la Iglesia                       0                              0
Émile Gaudreault                         0                              0
Éric Tessier                             0                              0
Étienne Faure                            0                              0
Total                                    1                              1

country                                             \
genres             Action|Adventure|Comedy|Fantasy
director_name
A. Raven Cruz                                    0
Aaron Hann                                       0
Aaron Schneider                                  0
Aaron Seltzer                                    0
Abel Ferrara                                     0
...                                            ...
Álex de la Iglesia                               0
Émile Gaudreault                                 0
Éric Tessier                                     0
Étienne Faure                                    0
Total                                            1

country                                                    ...    USA  \
genres             Action|Adventure|Drama|Romance|Western  ... Sci-Fi
director_name                                              ...
A. Raven Cruz                                           0  ...      0
Aaron Hann                                              0  ...      0
Aaron Schneider                                         0  ...      0
Aaron Seltzer                                           0  ...      0
Abel Ferrara                                            0  ...      0
...                                                   ...  ...    ...
Álex de la Iglesia                                      0  ...      0
Émile Gaudreault                                        0  ...      0
Éric Tessier                                            0  ...      0
Étienne Faure                                           0  ...      0
Total                                                   1  ...      2

country                                                               \
genres             Sci-Fi|Thriller Thriller Thriller|Western Western
director_name
A. Raven Cruz                    0        0                0       0
Aaron Hann                       0        0                0       0
Aaron Schneider                  0        0                0       0
Aaron Seltzer                    0        0                0       0
Abel Ferrara                     0        0                0       0
...                            ...      ...              ...     ...
Álex de la Iglesia               0        0                0       0
Émile Gaudreault                 0        0                0       0
Éric Tessier                     0        0                0       0
Étienne Faure                    0        0                0       0
Total                            9       12                1       7

country            United Arab Emirates                   West Germany  \
genres               Documentary|Family Adventure|Drama|Family|Fantasy
director_name
A. Raven Cruz                         0                              0
Aaron Hann                            0                              0
Aaron Schneider                       0                              0
Aaron Seltzer                         0                              0
Abel Ferrara                          0                              0
...                                 ...                            ...
Álex de la Iglesia                    0                              0
Émile Gaudreault                      0                              0
Éric Tessier                          0                              0
Étienne Faure                         0                              0
Total                                 1                              1

country                                                        Total
genres             Adventure|Drama|Thriller|War Horror|Mystery
director_name
A. Raven Cruz                                 0              0     1
Aaron Hann                                    0              0     1
Aaron Schneider                               0              0     1
Aaron Seltzer                                 0              0     1
Abel Ferrara                                  0              0     1
...                                         ...            ...   ...
Álex de la Iglesia                            0              0     1
Émile Gaudreault                              0              0     1
Éric Tessier                                  0              0     1
Étienne Faure                                 0              0     1
Total                                         1              1  4936

[2396 rows x 1549 columns]

### 4. Average duration of filmes grouped by color

In [35]:
pd.crosstab(moovies.genres, moovies.color, values=moovies.duration, aggfunc='mean', margins=True, margins_name="Total").fillna('-')

color,Black and White,Color,Total
genres,,,
Action,111.0,107.444444,107.800000
Action|Adventure,-,112.636364,112.636364
Action|Adventure|Animation|Comedy|Crime|Family|Fantasy,-,95.0,95.000000
Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi,-,96.0,96.000000
Action|Adventure|Animation|Comedy|Family,-,91.5,91.500000
...,...,...,...
Thriller,-,103.35,103.350000
Thriller|War,133.0,-,133.000000
Thriller|Western,85.0,-,85.000000
Western,-,106.0,106.000000
Total,112.253589,107.042908,107.260279

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [ ]:
pd.crosstab(moovies.genres, moovies.color, values=moovies.duration, aggfunc='mean', margins=True, margins_name="Total").fillna('-')

In [46]:
moovies['film_likes']=moovies['actor_3_facebook_likes']+moovies['actor_1_facebook_likes']+moovies['actor_2_facebook_likes']

In [51]:
moovies['director_likes']=moovies['cast_total_facebook_likes']-moovies['film_likes']

In [52]:
moovies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,film_likes,director_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,2791.0,2043.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,46000.0,2350.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,11554.0,146.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,73000.0,33759.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,1425.0,858.0
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,1753.0,0.0
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0.0,0.0
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,2154.0,232.0
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,125.0,38.0

In [58]:
directors=pd.crosstab(moovies.director_name, columns='Likes', values=moovies.director_likes, aggfunc='mean',margins=True, margins_name="Total").round(0)
directors

col_0                Likes   Total
director_name
A. Raven Cruz         94.0    94.0
Aaron Hann           370.0   370.0
Aaron Schneider     2360.0  2360.0
Aaron Seltzer       1941.0  1941.0
Abel Ferrara        1139.0  1139.0
...                    ...     ...
Álex de la Iglesia   238.0   238.0
Émile Gaudreault     116.0   116.0
Éric Tessier           7.0     7.0
Étienne Faure          0.0     0.0
Total                864.0   864.0

[2386 rows x 2 columns]

In [59]:
directors.head(10)

col_0              Likes   Total
director_name
A. Raven Cruz       94.0    94.0
Aaron Hann         370.0   370.0
Aaron Schneider   2360.0  2360.0
Aaron Seltzer     1941.0  1941.0
Abel Ferrara      1139.0  1139.0
Adam Brooks        119.0   119.0
Adam Carolla      1220.0  1220.0
Adam Goldberg      274.0   274.0
Adam Green        1309.0  1309.0
Adam Jay Epstein   281.0   281.0